[package]
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
name = "icalendar"
version = "0.10.0"
license = "MIT/Apache-2.0"
edition = "2018"

description = "Early, minimal icalendar crate."
keywords = ["calendar", "ical", "ics"]

documentation = "https://docs.rs/icalendar/"
repository = "https://github.com/hoodie/icalendar-rs"
readme = "README.md"

exclude = ["fixtures", ".github", ".gitignore", "*.json"]

[dependencies]
chrono = "0.4"

[dependencies.nom]
version = "7.1"
optional = true

[dependencies.uuid]
features = ["v4"]
version = "0.8"

[dev-dependencies]
pretty_assertions = "1"

[features]
default = []
parser = ["nom"]

[[example]]
name = "parse"
path= "examples/parse.rs"
required-features = ["parser"]

[[example]]
name = "full_circle"
path= "examples/full_circle.rs"
required-features = ["parser"]

[[example]]
name = "reserialize"
path= "examples/reserialize.rs"
required-features = ["parser"]
